#!/bin/bash

if [ -z "$1" ]
then
  echo "Please provide a branch name as the first arg"
  exit 1
fi

newBranch=$1

currentBranch=$(git symbolic-ref --short -q HEAD)
if [ $currentBranch != "master" ] 
then
  echo "please be on master yo"
  exit 1
fi

git pull
branchExists=$(git ls-remote --head origin refs/heads/$newBranch | wc -l)
if [ $branchExists = "0" ]
then
  echo "branch doesn't exist on remote"
  exit 1
fi

cleanFolderName=$(echo $newBranch | sed -e 's/\//-/g')
workTreeAddSuccess=$(git worktree add ../$cleanFolderName $newBranch)
if [ $workTreeAddSuccess = "branch doesn't exist on remote" ]
then
  echo workTreeAddSuccess
  exit 1
fi

if [ ! -f .env ]
then
  echo "env doesn't exist"
else
  echo "copying env file..."
  cp .env "../${cleanFolderName}"
fi

if [ ! -d node_modules]
then
  echo "node_modules doesn't exist"
else
  echo "copying node modules..."
  cp -r node_modules "../${cleanFolderName}"
fi
